hpdata <- read.table(text = grep("^[1,2]/2/2007",readLines("household_power_consumption.txt"),value=TRUE), sep = ';', col.names = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), na.strings = '?')
par(mfrow=c(2,2))
hpdata$Date <- as.Date(hpdata$Date, format = '%d/%m/%Y')
hpdata$Time <- as.POSIXct(paste(hpdata$Date, hpdata$Time))
plot(hpdata$Time, hpdata$Global_active_power, xlab = "", ylab = "Global Active Power", type = "l")
plot(hpdata$Time, hpdata$Voltage, xlab="datetime", ylab="Vpltage", type = "l")
plot(hpdata$Time, hpdata$Sub_metering_1, col="black", type = "l", ylab="Energy Sub Metering", xlab = "")
lines(hpdata$Time, hpdata$Sub_metering_2, col="red")
lines(hpdata$Time, hpdata$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd = 1)
plot(hpdata$Time, hpdata$Global_reactive_power, xlab = "datetime", ylab = "Global reactive power", type = "l")
